on: [push]

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_RUN_ID})
    - name:  Build the tagged Docker image
      run: docker build . --file Dockerfile --tag dnull88/prom-webui:${{steps.vars.outputs.tag}}
