on: [push]

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
    - uses: actions/checkout@v1
    - name:  Build the tagged Docker image
      run: docker build . --file Dockerfile --tag dnull88/prom-webui:${{steps.vars.outputs.tag}}
